    <!-- AltSenha -->
    <div class="con-settings">
        <div class="con-form-settings">
            <h4>Alterar Senha</h4>
            <p id="sub-title">Escolha uma senha segura para manter sua conta segura!</p>
            <form id="form_altSenha">
               
                <div class="single-input-whiteF">
                    <input name="senha" id="senha" type="password" required class="input">
                    <label class="p-medium" for="senha">Senha Atual</label>
                </div>
                <div class="single-input-whiteF">
                    <input name="senhaN" id="senhaN" type="password" required class="input">
                    <label class="p-medium" for="senhaN">Nova Senha</label>
                </div>
                <div class="single-input-whiteF">
                    <input name="senhaR" id="senhaR" type="password" required class="input">
                    <label class="p-medium" for="senhaR">Repita a Senha</label>
                </div>
                <button type="submit" class="btn-white" onclick="altSenha('/altSenha')">Alterar Senha</button>
            </form>
        </div>
    </div>


    <!--
    <div class="container-settings" id="pref">
    <div class="con-menu-settings">
        <h4>Alterar Senha</h4>
        <p id="sub-title">Escolha uma senha segura para manter sua conta segura!</p>
        <form action="/altSenha" method="post" class="configs" id="form_altSenha">
            <legend>Senha Atual</legend>
            <input name="senha" type="password" class="input-medium" id="senha" placeholder="Senha">
            

            <legend>Nova Senha</legend>
            <input name="senhaN" type="password" class="input-medium" id="senhaN" placeholder="Senha">

            <legend>Repita a Senha</legend>
            <input name="senhaR" type="password" class="input-medium" id="senhaR" placeholder="Senha">

            <button type="submit" onclick="altSenha('/altSenha')" class="btn-white">Alterar Senha</button>
        </form>
    </div>
    </div>-->