<img src="<?= $this->view->user_info['icone'] ?>" onclick="abrirModal('janela-modal-icones')">

<!-- <div class="con-img-profile-cont">
                    <img src="<?= $this->view->user_info['icone'] ?>" onclick="abrirModal('janela-modal-icones')">
                </div>
                <div class="name-profile" id="name-profile">    
                    <h4><?= $_SESSION['nome'] ?> <em class="p-small"> Nível <?= floor($this->view->user_info['nivel']) ?></em></h4>
                    <p class="p-small c-black"><?= $this->view->user_info['titulo'] ?></p>
                </div>
                <div class="con-dropdown" id="dropdown_profile">
                    <div class="con-btn-dropdown">
                        <a class="a-medium btn-green-square click-edit f-right">
                            <i class="fa-solid fa-gear"></i>
                            <em>Configurações</em>
                        </a>
                    </div>
                    <div class="list-dropdown">
                        <ul class="list-drop">
                            <li class="links-dropdown"><a onclick="requestPartial('/requestPartial?partial=preferences', 'con-control')">Preferências</a></li>
                            <li class="links-dropdown"><a onclick="requestPartial('/requestPartial?partial=altEmail', 'con-control')">Alterar E-mail</a></li>
                            <?php if($this->view->$user_info['senha'] != null) { ?>
                                <li class="links-dropdown"><a onclick="requestPartial('/requestPartial?partial=altSenha', 'con-control')">Alterar Senha</a></li>
                            <?php } ?>
                            <li class="links-dropdown"><a href="/sair">Sair</a></li>
                        </ul>
                    </div>
                </div> -->