<footer class="rod">

        <div class="rod-left">
            <img class="logo" src="img/AnyploVB.png">
        </div>

        <div class="rod-middle">          
            
        </div>

        <div class="rod-right">
            <div class="rod-right-nav">
                <a href="/aleatorio">Surpreenda-me</a>
                <a href="/mangas">Mangás</a>
                <a href="/lista">Minhas Listas</a>
                <a href="/categorias?status=Populares">Populares</a>
                <a href="/categorias?status=Lancamentos">Lançamentos</a>
                <a href="/categorias?status=MeAv">Melhores Avaliados</a>
                <a href="/categorias?status=Recem">Recém Atualizados</a>
            </div>
            <div class="rod-right-socials">
                <a href=""><i class="fa-brands fa-twitter"></i></a>
                <a href=""><i class="fa-brands fa-facebook"></i></a>
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                <a href=""><i class="fa-brands fa-discord"></i></a>
                <em>© Anyplo, Inc.</em>
            </div>
            
        </div>
        
    </footer>