
<!DOCTYPE html>
<html lang="pt-br">
<head>

    <!-- Title -->
    <title>Login</title>
    <script src="https://accounts.google.com/gsi/client" async defer></script>

    <style>
        body {
            background-image: url('../../img/<?= $this->view->bg ?>');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>

<body>
   
<?php require_once ("../App/views/partials/headerAlt.phtml") ?><!--Cabeçalho -->

    <div class="content">
        <div class="first-column">
            <div class="con-form">
                <h4>Iniciar Sessão</h4>
                <p>Já possui conta? Faça login aqui!</p>
                <?php if($this->view->login == 'erro') { ?>
                    <p class="c-red">Email ou senha inválido(s)!</p>
                <?php } ?>

                <?php if($this->view->msgSuccess) { ?>
                    <p class="c-green">Verifique seu e-mail para confirmar seu cadastro!</p>
                <?php } ?>

                <form action="/autenticar" method="post" class="form-up">
                    <div class="single-input-black">
                        <input name="login" id="login" required class="input">
                        <label class="p-medium" for="login">Nome de usuário ou E-mail</label>
                    </div>

                    <div class="single-input-black">
                        <input name="senha" id="senha" required class="input" type="password">
                        <label class="p-medium" for="senha">Senha</label>
                    </div>
                    <button class="btn-green-BW" type="submit">Iniciar Sessão</button>
                    <p>Não possui conta? <a href="/register" class="c-green"> Registre-se</a></p>
                    <p>Ou</p>

                    <div id="g_id_onload"
                        data-client_id="1096694795774-8rnonr531bi05i337emsstfvqjpmd6e3.apps.googleusercontent.com"
                        data-login_uri="/login_google"
                        data-auto_prompt="false">
                    </div>
                    <div class="g_id_signin"
                        data-type="standard"
                        data-size="large"
                        data-shape="pill"
                        data-theme="outline"
                        data-text="sign_in_with"
                        data-shape="rectangular"
                        data-logo_alignment="left">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <?php require_once ("../App/views/partials/footer.phtml") ?><!-- Footer/Rodapé -->
    </main>
    
</body>
</html>