<div class="header-admin-g">
    <h3>Adicionar Título</h3>
</div>
<div class="body-admin-gg">
<form action="/addTitle" enctype="multipart/form-data" method="post" class="form-gerenciar">
                        <div class="single-input-black">
                            <input type="text" name="nome" id="nome" required class="input" >
                            <label class="p-medium" for="nome">Nome do Título</label>
                        </div>
                        <div class="single-input-black">
                            <input type="number" name="nivel" id="nivel" required class="input" >
                            <label class="p-medium" for="nivel">Nível 0 - 1000</label>
                        </div>
                        <button type="submit" class="btn-green-small-BW">Enviar Título</button>
                    </form>
</div>
