<h5>Editar Ano de lançamento</h5>
<form action="/acaoAdmin?acaoAdmin=updateAno_lanc" method="post" class="form-gerenciar">
    <div class="single-select-black" id="con-control">
            <select name="id_manga" class="input" required>
                <option value="" selected>---</option>
                <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                    <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?></option>
                <?php } ?>
            </select>
            <i class="fa-solid fa-caret-down"></i>
            <label class="p-medium" for="id_manga">Nome</label>
    </div>
    
    <div class="single-input-black">
        <input name="ano_lancN" id="ano_lancN" required class="input" >
        <label class="p-medium" for="ano_lancN">Ano de Lançamento</label>
    </div>
    <button type="submit" class="btn-green-small-BW">Editar Ano de Lançamento</button>
</form>
