<h5>Editar background</h5>
    <form action="/acaoAdmin?acaoAdmin=updatePathB" enctype="multipart/form-data" method="post" class="form-gerenciar">

        <div class="single-select-black" id="con-control">
            <select name="id_manga" class="input" required>
                <option value="" selected>---</option>
                <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                    <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?></option>
                <?php } ?>
            </select>
            <i class="fa-solid fa-caret-down"></i>
            <label class="p-medium" for="id_manga">Nome</label>
        </div>
        <label onclick="BgPreview()" for="arquivoBg" class="btn-green-small">Selecionar Background</label>
        <input type="file" name="back" id="arquivoBg" class="input-small" required>
        <img class="img-preview-bg" id="img-BG" alt="">
        <button type="submit" class="btn-green-small-BW">Editar Background</button>
    </form>
