<div class="header-admin-g">
    <h3>Deletar Título</h3>
</div>
<div class="body-admin-gg">
<form action="/removerTitle" enctype="multipart/form-data" method="post" class="form-gerenciar">
                    <div class="single-select-black" id="con-control">
                        <select name="id_titulo" class="input" required>
                            <option value="" selected>---</option>
                            <?php foreach($this->view->title as $indice_arr => $title) { ?>
                                <option value="<?= $title['id'] ?>"><?= $title['nome'] ?> </option>
                            <?php } ?>
                        </select>
                        <i class="fa-solid fa-caret-down"></i>
                        <label class="p-medium" for="id_categoria">Título</label>
                    </div>
                    <button type="submit" class="btn-green-small-BW">Deletar Título</button>
                    </form>
</div>