<div class="header-admin-g">
    <h3>Deletar Scan</h3>
</div>
<div class="body-admin-gg">
<form action="/removerScan" enctype="multipart/form-data" method="post" class="form-gerenciar">
                    <div class="single-select-black" id="con-control">
                        <select name="idScan" class="input" required>
                            <option value="" selected>---</option>
                            <?php foreach($this->view->scans as $indice_arr => $scan) { ?>
                                <option value="<?= $scan['id'] ?>"><?= $scan['nome'] ?> </option>
                            <?php } ?>
                        </select>
                        <i class="fa-solid fa-caret-down"></i>
                        <label class="p-medium" for="id_categoria">Scan</label>
                    </div>
                    <button type="submit" class="btn-green-small-BW">Deletar Scan</button>
                    </form>
</div>