
<div class="header-admin-g">
    <h3>Deletar Capítulo</h3>
</div>
<div class="body-admin-gg">
<form action="/removerCap" enctype="multipart/form-data" method="post" class="form-gerenciar">
                    <div class="single-select-black" id="con-control">
                            <select name="id_manga" class="input" id="select_manga_delete" onchange="requestCap('select_manga_delete', 'con-control-select-cap-delete')" required>
                                <option value="" selected>---</option>
                                <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                                    <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?></option>
                                <?php } ?>
                            </select>
                            <i class="fa-solid fa-caret-down"></i>
                            <label class="p-medium" for="id_manga">Nome</label>
                        </div>

                        <div class="single-select-black" id="con-control-select-cap-delete">
                            <select name="n_cap" class="input" required>
                                <option value="" selected>---</option>
                                <?php foreach($this->view->cap as $indice_arr => $cap) { ?>
                                    <option value="<?= $cap['n_cap'] ?>"><?= $cap['n_cap'] ?> </option>
                                <?php } ?>
                            </select>
                            <i class="fa-solid fa-caret-down"></i>
                            <label class="p-medium" for="n_cap">Nº do Capítulo</label>
                        </div>
                        <button type="submit" class="btn-green-small-BW">Deletar Capítulo</button>
                    </form>  
</div>
