<div class="header-admin-g">
                <h3>Deletar Mangá</h3>
            </div>
            <div class="body-admin-gg">
                <form action="/removerManga" enctype="multipart/form-data" method="post" class="form-gerenciar">
                   <div class="single-select-black" id="con-control">
                        <select name="id_manga" class="input" required>
                            <option value="" selected>---</option>
                            <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                                <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?> </option>
                            <?php } ?>
                        </select>
                        <i class="fa-solid fa-caret-down"></i>
                        <label class="p-medium" for="id_manga">Nome</label>
                    </div>
                    <button type="submit" class="btn-green-small-BW">Deletar Mangá</button>
                </form>
            </div>