<div class="header-admin-g">
    <h3>Editar Grupos</h3>
</div>
            <div class="body-admin-edit">
                <div class="header-admin-edit">
                    <a onclick="requestPartial('/requestPartialAdmin?partial=nomeScanEdit', 'con-admin-edit')">Nome</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=logoScanEdit', 'con-admin-edit')">Logo</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=siteScanEdit', 'con-admin-edit')">Site</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=facebookScanEdit', 'con-admin-edit')">Facebook</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=discordScanEdit', 'con-admin-edit')">Discord</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=twitterScanEdit', 'con-admin-edit')">Twitter</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=doarScanEdit', 'con-admin-edit')">Link de Doação</a>
                </div>
                <div class="con-admin-edit" id="con-admin-edit">
                    
                </div>
            </div>