<div class="header-admin-g">
    <h3>Editar Título</h3>
</div>
<div class="body-admin-edit">
        <div class="header-admin-edit">
            <a onclick="requestPartial('/requestPartialAdmin?partial=titleEdit', 'con-admin-edit')">Nome</a>
            <a onclick="requestPartial('/requestPartialAdmin?partial=nivelEdit', 'con-admin-edit')">Nível</a>
        </div>
        <div class="con-admin-edit" id="con-admin-edit">

        </div>
</div>