<div class="header-admin-g">
    <h3>Editar Capítulo</h3>
</div>
<div class="body-admin-gg">
<form action="/editCap" enctype="multipart/form-data" method="post" class="form-gerenciar">


                        <div class="single-select-black" id="con-control">
                            <select name="id_manga" class="input" id="select_manga" onchange="requestCap('select_manga', 'con-control-select-cap')" required>
                                <option value="" selected>---</option>
                                <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                                    <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?></option>
                                <?php } ?>
                            </select>
                            <i class="fa-solid fa-caret-down"></i>
                            <label class="p-medium" for="id_manga">Nome</label>
                        </div>

                        <div class="single-select-black" id="con-control-select-cap">
                            <select name="n_cap" class="input" required>
                                <option value="" selected>---</option>
                                <?php foreach($this->view->cap as $indice_arr => $cap) { ?>
                                    <option value="<?= $cap['n_cap'] ?>"><?= $cap['n_cap'] ?> </option>
                                <?php } ?>
                            </select>
                            <i class="fa-solid fa-caret-down"></i>
                            <label class="p-medium" for="n_cap">Nº do Capítulo</label>
                        </div>

                        <div class="single-input-black">
                            <input type="text" name="n_capN" id="n_capN" required class="input" >
                            <label class="p-medium" for="n_capN">Novo Nº do Capítulo</label>
                        </div>
                        <button type="submit" class="btn-green-small-BW">Editar Capitulo</button>
                    </form>
</div>
