<div class="header-admin-g">
                <h3>Editar Mangá</h3>
            </div>
            <div class="body-admin-edit">
                <div class="header-admin-edit">
                    <a onclick="requestPartial('/requestPartialAdmin?partial=imgEdit', 'con-admin-edit')">Imagem</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=bgEdit', 'con-admin-edit')">Background</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=nomeEdit', 'con-admin-edit')">Nome</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=generoEdit', 'con-admin-edit')">Gêneros</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=statusEdit', 'con-admin-edit')">Status</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=tipoEdit', 'con-admin-edit')">Tipo</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=anoEdit', 'con-admin-edit')">Ano de Lançamento</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=sinopseEdit', 'con-admin-edit')">Sinopse</a>
                </div>
                <div class="con-admin-edit" id="con-admin-edit">
                    
                </div>
            </div>