<div class="header-admin-g">
    <h3>Editar Categoria</h3>
</div>
            <div class="body-admin-edit">
                <div class="header-admin-edit">
                    <a onclick="requestPartial('/requestPartialAdmin?partial=nomeCatEdit', 'con-admin-edit')">Nome</a>
                    <a onclick="requestPartial('/requestPartialAdmin?partial=descEdit', 'con-admin-edit')">Descrição</a>
                </div>
                <div class="con-admin-edit" id="con-admin-edit">
                    
                </div>
            </div>