<h5>Editar Nome</h5>
<form action="/acaoAdmin?acaoAdmin=updateNomeCategoria" enctype="multipart/form-data" method="post" class="form-gerenciar">
    <div class="single-select-black" id="con-control">
        <select name="id_categoria" class="input" required>
            <option value="" selected>---</option>
            <?php foreach($this->view->categorias as $indice_arr => $categoria) { ?>
                <option value="<?= $categoria['id'] ?>"><?= $categoria['nome'] ?> </option>
            <?php } ?>
        </select>
        <i class="fa-solid fa-caret-down"></i>
        <label class="p-medium" for="id_categoria">Nome</label>
    </div>

    <div class="single-input-black">
        <input type="text" name="nomeN" id="nomeN" required class="input" >
        <label class="p-medium" for="nomeN">Nome Editado</label>
    </div>
    <button type="submit" class="btn-green-small-BW">Editar Nome</button>
</form>