<h5>Editar Status</h5>
<form action="/acaoAdmin?acaoAdmin=updateStatus" method="post" class="form-gerenciar">
    <div class="single-select-black" id="con-control">
            <select name="id_manga" class="input" required>
                <option value="" selected>---</option>
                <?php foreach($this->view->mangas as $indice_arr => $manga) { ?>
                    <option value="<?= $manga['id'] ?>"><?= $manga['nome'] ?> | <?= $manga['tipo'] ?></option>
                <?php } ?>
            </select>
            <i class="fa-solid fa-caret-down"></i>
            <label class="p-medium" for="id_manga">Nome</label>
        </div>

        <div class="single-select-black" id="con-control">
            <select name="statusN" class="input" required>
                <option value="" selected>---</option>
                <?php foreach($this->view->status as $indice_arr => $manga) { ?>
                    <?php if($manga['nome'] == "Recém Atualizados" || $manga['nome'] == "Melhores Avaliados") { ?>
                        <option disabled value="<?= $manga['nome'] ?>"><?= $manga['nome'] ?></option>
                    <?php } else { ?>
                        <option value="<?= $manga['nome'] ?>"><?= $manga['nome'] ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
            <i class="fa-solid fa-caret-down"></i>
            <label class="p-medium" for="id_manga">Status</label>
        </div>
    <button type="submit" class="btn-green-small-BW">Editar Status</button>
</form>