<?php error_reporting(0); ini_set('display_errors', '0'); ?>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

		<!-- Meta tags -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--JS mobile-menu -->
		<script src="js/mobile-navbar.js" defer></script>

		<!-- JavaScript Modal_Mobile_Menu -->
		<script src="js/modal_mobile_menu.js" defer></script>

		<!-- Font Awesome -->
		<script src="https://kit.fontawesome.com/a2b163b64e.js" crossorigin="anonymous"></script>
		
		<!-- HTML5Shiv -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<![endif]-->

		<!-- Dark_mode -->
		<script src="js/dark_mode.js" defer></script>

		<!-- Dark_mode -->
		<script>
			const changeThemeToDark = () => {
				document.documentElement.setAttribute("data-theme", "dark");
				localStorage.setItem("data-theme", "dark");
			}

			const changeThemeToLight = () => {
				document.documentElement.setAttribute("data-theme", "light");
				localStorage.setItem("data-theme", 'light');
			}
			let theme = localStorage.getItem('data-theme');
			if (theme == 'dark') changeThemeToDark();
		</script>


		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>